### ISSUE TITLE
Maintain output in console

### ISSUE THREAD

**Issue by chasemccoy** [stevenpetryk/eleventy-plugin-error-overlay#1]
I love this plugin! Great work. The only thing that I wish was different is that I can no longer see error output in my terminal... I would love if the error could be shown in both the browser _and_ the terminal, so I can see it wherever I happen to be working. Sometimes I'm working on something and I'm not jumping back and forth to the browser, in which case I miss the error output unless I go check there.

**Comment by stevenpetryk** [comment]
Oh shoot, didn’t even notice! Let me look into that today. Also, there’s a PR to merge this into the core and I’m certain it doesn’t have the same issue.

**Comment by chasemccoy** [comment]
Wonderful, thank you!

**Comment by stevenpetryk** [comment]
No prob! It's now available in `0.1.2`.
